feat: add meta tags
eoscostarica/eoscostarica.io pull request #218
Opened 2021-02-01 15:24 UTC by JeanVegaD

closes #117

# What does this PR do?
- add meta tags to website

2021-02-05 15:26 UTC, xavier506 commented
@JeanVegaD  can we use this image instead for the social media preview please 
![social-media-preview](https://user-images.githubusercontent.com/5632966/107053185-29db7100-6794-11eb-9cae-9c722f9485e4.png)

2021-02-05 15:27 UTC, xavier506 commented on docusaurus.config.js
> +      {name: 'og:image', content: 'https://raw.githubusercontent.com/eoscostarica/eoscostarica.io/master/static/img/eoscr-logo.png'},
please change for attached image

2021-02-05 15:27 UTC, xavier506 requested changes
update social media image

2021-02-09 22:07 UTC, AngeloCG97 approved these changes

2021-02-09 22:09 UTC, merged